# Generated by Django 4.0.2 on 2022-03-04 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choicer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
