# Generated by Django 4.0.2 on 2022-03-04 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_alter_board_likey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='likey',
            field=models.ManyToManyField(blank=True, related_name='likey', to=settings.AUTH_USER_MODEL),
        ),
    ]
